# Author: David Tigreros
# 8/11/2016
# CS-260 Section-003
# Programming Assignment 2
# Makefile

.PHONY: clean

pointerqueue:
	@chmod 755 .
	@python pointerqueue_test.py

loctree:
	@chmod 755 .
	@python loctree_test.py

lcrstree:
	@chmod 755 .
	@python lcrstree_test.py

time:
	@chmod 755 .
	@python timing.py

mergelists:
	@chmod 755 .
	@python mergelists.py

listconcat:
	@chmod 755 .
	@python listconcat.py

levelorder:
	@chmod 755 .
	@python levelorder.py
	
preorder:
	@chmod 755 .
	@python preorder.py

postorder:
	@chmod 755 .
	@python postorder.py

clean:
	@\rm -f *.pyc
