# Author: David Tigreros
# 7/29/2016
# CS-260 Section 003
# Dr. Nowak
# Programming Assignment 1
# Makefile

.PHONY: clean

time:
		@chmod 755 .
		@python timing.py

pointerlist:
		@chmod 755 .
		@python pointerlist.py

arraylist:
		@chmod 755 .
		@python arraylist.py

pointerstack:
		@chmod 755 .
		@python pointerstack.py

arraystack:
		@chmod 755 .
		@python arraystack.py

clean:
		@\rm -f *.pyc
