CC=gcc
CCX=g++
RM = rm -rf
headers :=										\
					ReadabilityIndex.h	\

sources :=											\
					ReadabilityIndex.cpp	\
					main.cpp

all: readability

readability:
	$(CCX) -Wall -o readability main.cpp

clean:
	$(RM) readability
